version: 0.1

phases:
  install:
            runtime-versions:
            nodejs: 12
        commands:
            - echo "installing something"
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --prod
  post_build:
       commands:
        - echo "we are in the post bild build phase"
artifacts:
  files:
    - "**/*"
  discard-paths: no
