#!/bin/sh
ssh ec2-user@13.127.230.126 <<EOF
    cd ~/Calculator-Aoo-Angular
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    npm install v10.11.0
    npm install
    npm install -g nodemon pm2
    npm install -g @angular/cli
    pm2 restart ecosystem.config.js
    exit
EOF
